WSUS へスキャンを行うクライアントのセキュリティ向上の為の変更点
jpmem/blog pull request #106
Opened 2022-01-12 04:34 UTC by KaitoAoki

新規で記事を作成しましたので、レビューお願いします。

2022-01-12 04:34 UTC, KaitoAoki commented
/ok-to-preview sha=f374910e

2022-01-15 04:55 UTC, tkaji-w commented
抄訳元記事へのリンクを張りましょう。また、段落変更以外で改行はしないのがルールになってますので、対応お願いします。

2022-01-27 10:23 UTC, yuhonda requested changes

2022-01-27 10:23 UTC, yuhonda commented on articles/wsus/2020-09-08_01.md
> +みなさん、こんにちは。WSUS サポート チームです。
皆様、のほうがいいですかね。

2022-01-27 10:23 UTC, yuhonda commented on articles/wsus/2020-09-08_01.md
> +Microsoft Update (WSUS を含む) は、コンテンツファイルとカタログ情報 (メタデータ) という 2 種類のコンテンツに依存しています。どちらののコンテンツも非常に重要であり、コンピュータを安全かつ最新の状態に保つために、どちらも保護する必要がございます。
typo あります。どちらのの

2022-01-27 10:23 UTC, yuhonda commented on articles/wsus/2020-09-08_01.md
> +更新プログラムのコンポーネントを含む実体のファイルです。デジタル署名チェックや暗号ハッシュ検証など、複数の手段で改ざんから保護されています。HTTPS は、データが信頼できることを証明するためにクライアントが使用する適切なチェーン・オブ・カストディを提供します。
更新プログラムの実体となるファイルそのものです。　のほうがわかりやすいですね。チェーン・オブ・カストディは、Chain of Custody としておきましょうか。

2022-03-10 01:22 UTC, merged

2022-03-10 01:23 UTC, yuhonda commented
Approved