Add artichle for eHTTP check and fix certificate
jpmem/blog pull request #112
Opened 2022-01-22 08:05 UTC by tkaji-w

2022-01-27 10:11 UTC, yuhonda requested changes

2022-01-27 10:11 UTC, yuhonda commented on articles/mecm/20220122_01.md
> +title: 拡張 HTTP 接続の確認方法 (サーバー 観点)
ちょっとタイトルがわかりにくいです。MEM のブログなので、Configuration Manager における拡張 HTTP 設定の確認方法、くらいでいいんじゃないでしょうか。

2022-01-27 10:11 UTC, yuhonda commented on articles/mecm/20220122_01.md
> +1. サイト 設定
設定、の前の半角スペース不要です。

2022-01-27 10:11 UTC, yuhonda commented on articles/mecm/20220122_01.md
> +2. 管理ポイント 設定
同上

2022-01-27 10:11 UTC, yuhonda commented on articles/mecm/20220122_01.md
> +3. 配布ポイント 設定
同上

2022-01-27 10:11 UTC, yuhonda commented on articles/mecm/20220122_01.md
> +- サイト システム の設定にて、[HTTPS または HTTP] が選択されている。
の設定、の前の半角スペース不要です。

2022-01-27 10:11 UTC, yuhonda commented on articles/mecm/20220122_01.md
> +## 管理ポイント 設定
設定、の前の半角スペース不要です。

2022-01-27 10:11 UTC, yuhonda commented on articles/mecm/20220122_01.md
> +## 配布ポイント 設定
設定、の前の半角スペース不要です。

2022-01-27 10:11 UTC, yuhonda commented on articles/mecm/20220122_01.md
> +## IIS マネージャー の バインド 設定
マネージャーの後、バインド前後の半角スペース不要です。

2022-01-27 10:11 UTC, yuhonda commented on articles/mecm/20220122_01.md
> +### バインド 設定の修復方法
設定、の前の半角スペース不要です。

2022-01-28 04:38 UTC, tkaji-w commented
ありがとうございます。修正しました。

2022-02-04 00:02 UTC, merged