Rikusaka0401
jpmem/blog pull request #126
Opened 2022-03-29 10:59 UTC by rikusaka

[Add CM Blog Post 2022/04/01 マスターイメージ取得手順]
のレビューをお願い致します。

2022-03-29 11:17 UTC, yuhonda requested changes

2022-03-29 11:17 UTC, yuhonda commented on articles/mecm/20220401_01.md
> +・System Center Configuration Manager LTSB
マークダウンの場合・ではなく - をつかってください。

2022-03-29 11:17 UTC, yuhonda commented on articles/mecm/20220401_01.md
> +・Microsoft Endpoint Configuration Manager (Current Branch)
同上。

2022-03-29 11:17 UTC, yuhonda commented on articles/mecm/20220401_01.md
> +5. SMSSLP または DNSSUFFIX のレジストリ値を設定する (任意)
昔はすべてのオプション指定がNGだったので、この章を追加していたのですが、最新の docs だと、SMSSITECODE オプションの指定はNGですが、それ以外のオプション指定がNGという指定はないので、この章は消してください。
参考）https://docs.microsoft.com/ja-jp/mem/configmgr/core/clients/deploy/deploy-clients-to-windows-computers#prepare-the-client-computer-for-imaging
ーーー
 重要
クライアントの Configuration Manager サイト コードは、コマンド ライン プロパティCCMSetup.exe指定しない。
ーーー

2022-03-29 11:17 UTC, yuhonda commented on articles/mecm/20220401_01.md
> +※オプションなしで ccmsetup.exe を実行することにより、"未割り当て" の状態でエージェントがセットアップされます。
SMSSITECODE オプションなしで、に変更してください。

2022-03-29 11:17 UTC, yuhonda commented on articles/mecm/20220401_01.md
> +### 5. SMSSLP または DNSSUFFIX のレジストリ値を設定する (任意)
この章は不要です。

2022-03-29 11:17 UTC, yuhonda commented on articles/mecm/20220401_01.md
> +1) Windows キー + R キーを押下し、**certlm.msc** を実行し、ローカル コンピューターの証明書ストアを開きます。
項番は 1. 2. 3. 4. で統一しましょう。

2022-03-29 11:17 UTC, yuhonda commented on articles/mecm/20220401_01.md
> +※本記事は、以下の 2 つの過去記事を取り纏めたものとなります。
※本記事は、以下の 2 つの過去記事を最新の情報をもとに取り纏めたものとなります。  

としましょう。（レジストリの章を削除しているので）

2022-03-30 07:04 UTC, rikusaka commented on articles/mecm/20220401_01.md
> +5. SMSSLP または DNSSUFFIX のレジストリ値を設定する (任意)
5. SMSSLP または DNSSUFFIX のレジストリ値を設定する (任意)
この章を削除で良いですか？

2022-03-31 07:14 UTC, yuhonda requested changes

2022-03-31 07:14 UTC, yuhonda commented on articles/mecm/20220401_01.md
> +
ワークグループ環境の場合は、SMSMP もしくは DNSSUFFIX オプションなどを任意で指定してください。ただし、その場合も SMSSITECODE オプションは使用しないようにしてください。

2022-04-14 06:40 UTC, yuhonda commented
違う記事のファイルがはいっているので、再度提出ください

2022-04-14 06:40 UTC, closed without merging