Configuration Manager ReportServer データベースのトランザクションログ肥大化への対策　の見た目修正
jpmem/blog pull request #227
Opened 2023-01-18 08:34 UTC by KaitoAoki

こちらのブログの SQL クエリ等の見た目が崩れていた為、旧ブログを参考に見た目を整えました。

旧ブログ
https://learn.microsoft.com/ja-jp/archive/blogs/systemcenterjp/configuration-manager-reportserver-transaction-log-management

2023-01-18 08:34 UTC, KaitoAoki commented
/ok-to-preview sha=e7e93df0

2023-01-19 00:06 UTC, yuhonda requested changes
URL チェックお願いします。

2023-01-19 00:06 UTC, yuhonda commented on articles/mecm/20180629_01.md
>    http://msdn.microsoft.com/ja-jp/library/ms191164(v=sql.100).aspx
このあたりのリンクもリンク切れである可能性あるので、チェックして修正してもらえるとたすかります。docs.microsoft.com は learn.microsoft.com のほうにしておいてください。

2023-01-19 03:58 UTC, KaitoAoki commented
URL を修正しました。ご確認お願いいたします。
不足が在りましたらお手数をおかけしますが教えて頂けますと幸いです。

2023-01-20 01:00 UTC, yuhonda approved these changes
Approved

2023-01-20 01:00 UTC, merged