Tahakogi
jpmem/blog pull request #240
Opened 2023-03-17 05:40 UTC by tahakogi

自習書シリーズの新規時作成をしましたのでレビューをお願いします

2023-03-17 05:41 UTC, tahakogi commented
/ok-to-preview sha=0a757591

2023-03-17 05:49 UTC, yuhonda requested changes
1カ所修正お願いします

2023-03-17 05:49 UTC, yuhonda commented on articles/mecm/20230316_01.md
> +主にオンプレミスにあるデバイスを管理する目的の製品群である System Center 製品ファミリしたが、現在は上記のように **Microsoft Cloud のパワーを利用しながら、Configuration Manager への既存の投資を活かしつづける** ことが現在の Intune 製品ファミリとなった背景です。
2カ所タイポがあります。ファミリー、ですね。

2023-03-20 04:09 UTC, yuhonda requested changes
1点修正お願いします。

2023-03-20 04:09 UTC, yuhonda commented on articles/mecm/20230316_01.md
> +その後 Systems Management Server 2003 、System Center Configuration Manager 2007 、System Center Configuration Manager 2012 を経て現在の Configuration Manager (Current Branch) に進化してきた歴史があります。
System Center 2012 Configuration Manager ですね。なので、

System Center 2012 Configuration Manager を経て現在の Microsoft Configuration Manager (Current Branch) に進化してきた歴史があります。

が正確ですね。

2023-03-20 04:16 UTC, tkaji-w approved these changes

2023-03-20 04:31 UTC, tahakogi commented on articles/mecm/20230316_01.md
> +その後 Systems Management Server 2003 、System Center Configuration Manager 2007 、System Center Configuration Manager 2012 を経て現在の Configuration Manager (Current Branch) に進化してきた歴史があります。
ありがとうございました。修正しました

2023-03-20 04:55 UTC, tahakogi commented
指摘いただいた件は全部修正済みです

2023-03-20 05:07 UTC, yuhonda approved these changes
approved

2023-03-20 05:07 UTC, merged