Configuration Manager から展開できる機能のご紹介
jpmem/blog pull request #251
Opened 2023-03-30 07:01 UTC by kojiyamada0811

新規作成しましたので、レビューをお願いします。

2023-03-30 08:19 UTC, yuhonda requested changes
1カ所修正お願いします。

2023-03-30 08:19 UTC, yuhonda commented on articles/mecm/20230330_02.md
> +OS をアップグレードする機能更新プログラムや品質更新プログラム、Defender の定義ファイルの更新、Microsoft 365 の更新プログラムなどを展開できる機能です。
Defender の定義ファイルの更新＞Microsoft Defender ウイルス対策のセキュリティ インテリジェンス更新プログラム、
Microsoft 365 の更新プログラム > Microsoft 365 Apps の更新プログラム、ですね。

製品名称は公式のものをつかうようにしてください。

2023-07-20 06:16 UTC, soheiogata commented on articles/mecm/20230330_02.md
> +OS をアップグレードする機能更新プログラムや品質更新プログラム、Defender の定義ファイルの更新、Microsoft 365 の更新プログラムなどを展開できる機能です。
修正しました

2023-07-20 07:32 UTC, yuhonda requested changes
3点修正お願いします。

2023-07-20 07:32 UTC, yuhonda commented on articles/mecm/20230330_02.md
> +date: 2023-03-30
古いので、date 変更してください。

2023-07-20 07:32 UTC, yuhonda commented on articles/mecm/20230330_02.md
> +title: Configuration Manager ベーシック ナレッジ シリーズ 1 - Configuration Manager から展開できる機能のご紹介
このシリーズは継続されますか？

2023-07-20 07:32 UTC, yuhonda commented on articles/mecm/20230330_02.md
> +  - MECM
シリーズ化するならタグつけるとどうでしょう。

2023-07-20 08:25 UTC, soheiogata commented on articles/mecm/20230330_02.md
> +date: 2023-03-30
7/20 に変更しました。

2023-07-20 08:26 UTC, soheiogata commented on articles/mecm/20230330_02.md
> +title: Configuration Manager ベーシック ナレッジ シリーズ 1 - Configuration Manager から展開できる機能のご紹介
継続します。

2023-07-20 08:26 UTC, soheiogata commented on articles/mecm/20230330_02.md
> +  - MECM
タグ付けました

2023-07-20 08:31 UTC, merged