WSUS コンソール上での Windows 11 の OS 表示について
jpmem/blog pull request #264
Opened 2023-06-01 07:40 UTC by tahakogi

ユーザーからの要望で記事を作成しましたのでレビューをお願いします。

2023-06-01 07:41 UTC, tahakogi commented
/ok-to-preview sha=202f783a

2023-06-05 01:58 UTC, tahakogi commented
プルリクエストを本ブログ内容のみに修正済み

2023-06-06 06:55 UTC, yuhonda requested changes
3点修正お願いします。

2023-06-06 06:55 UTC, yuhonda commented on articles/mecm/20230601_01.md
> +date:   2023-05-31
20230601_01.md となっているので、date は 2023-06-01 としましょう。

2023-06-06 06:55 UTC, yuhonda commented on articles/mecm/20230601_01.md
> +title:  WSUS コンソール上での Windows 11 の OS 名称について
WSUS で Windows 11 クライアントが Windows 10 と表示される事象について、にしましょうか。

2023-06-06 06:55 UTC, yuhonda commented on articles/mecm/20230601_01.md
> +本事象は該当のクライアント上の情報が Windows 10 と Windows 11 で共通であるため発生いたしますが、表示上の問題であり更新プログラムの管理動作には影響はございません。
該当のクライアント上の情報＞クライアント バージョンを判断するための情報、にしましょう。

2023-06-06 07:01 UTC, yuhonda approved these changes
approved

2023-06-06 07:01 UTC, merged

2023-06-06 07:02 UTC, tahakogi commented
レビュー内容を修正しました！