Microsoft Configuration Manager 自習書シリーズ 2 Microsoft Configuration Manager FAQ
jpmem/blog pull request #265
Opened 2023-06-07 08:30 UTC by tahakogi

EMS ライセンス契約保有状況でたまにあるライセンス発行のSRを抑止したい目的で書きました

2023-06-07 08:31 UTC, tahakogi commented
/ok-to-preview sha=bfae3775

2023-06-08 01:42 UTC, yuhonda requested changes
修正お願いします

2023-06-08 01:42 UTC, yuhonda commented on articles/mecm/22030607_01.md
> +title:  Microsoft Configuration Manager 自習書シリーズ 2 Microsoft Configuration Manager FAQ
自習書で FAQ の転記を書く必要も無いかと思うので、ライセンスに関するブログ記事を書きたいのであれば、ライセンスに関することをお伝えするタイトルにしましょう。

2023-06-08 01:42 UTC, yuhonda commented on articles/mecm/22030607_01.md
> +## Configuration Manager と Microsoft Intune 製品ファミリで何が変わりますか?
ライセンスに関する記事であれば、この項目は不要かな、とおもいました。それか、ライセンスに関してどのような変更があるかを書いた方が良い。

2023-06-08 01:42 UTC, yuhonda commented on articles/mecm/22030607_01.md
> +今回は [Microsoft Configuration Manager FAQ](https://learn.microsoft.com/ja-jp/mem/configmgr/core/understand/configuration-manager-faq) について解説していきます。
ライセンスに関する FAQ として紹介した方がいいかな。

2023-08-18 06:48 UTC, tahakogi commented
いったん再クローンのため取り下げます

2023-08-18 06:48 UTC, closed without merging