Add CM Blog post 2023/08/18 再投稿
jpmem/blog pull request #291
Opened 2023-08-18 07:00 UTC by tahakogi

前のプルリクエストを閉じて出し直しです

2023-08-18 07:01 UTC, tahakogi commented
/ok-to-preview sha=d8c39052

2023-08-29 00:58 UTC, yuhonda requested changes
6点修正お願いします。

2023-08-29 00:58 UTC, yuhonda commented on articles/mecm/20230818_01.md
> +
以下の免責をつけてご案内ください。

# 免責事項
下記内容は XXXX/XX/XX 時点での内容についての記載となっております。
今後内容が更新されることもございますので、最新情報は以下の公開情報をご確認ください。
[Configuration Manager ブランチとライセンスについてよく寄せられる質問](https://learn.microsoft.com/ja-jp/mem/configmgr/core/understand/product-and-licensing-faq)

2023-08-29 00:58 UTC, yuhonda commented on articles/mecm/20230818_01.md
> +## 管理するためのサーバー（管理ポイントやソフトウェア更新ポイントなど）側にライセンスは必要ですか？
見出し1は、# 1個だけで大丈夫です。

2023-08-29 00:58 UTC, yuhonda commented on articles/mecm/20230818_01.md
> +## プライマリ サイトや中央管理サイトのインストール時に求められるライセンス キーはどこから入手できますか？
同上

2023-08-29 00:58 UTC, yuhonda commented on articles/mecm/20230818_01.md
> +## Microsoft Intune 製品ファミリの共同管理のライセンスに関する変更点
同上

2023-08-29 00:58 UTC, yuhonda commented on articles/mecm/20230818_01.md
> +サイト自体を新規インストールする場合には VLSC から旧環境構築時に利用したプロダクト キーを入手いただいて利用ください。
VLSC など、としてください。

2023-08-29 00:58 UTC, yuhonda commented on articles/mecm/20230818_01.md
> +>以前にSystem Center Configuration Manager に対して持っていたライセンスは、引き続き Microsoft Configuration Managerに適用されます。 新しいサイトをインストールする場合は、既存のプロダクト キーを使用してください。
以前にSystem Center Configuration Manager 
＞半角スペースお願いします。

2023-09-01 07:42 UTC, tahakogi commented on articles/mecm/20230818_01.md
> +
追記済み

2023-09-01 07:42 UTC, tahakogi commented on articles/mecm/20230818_01.md
> +## 管理するためのサーバー（管理ポイントやソフトウェア更新ポイントなど）側にライセンスは必要ですか？
削除済み

2023-09-01 07:42 UTC, tahakogi commented on articles/mecm/20230818_01.md
> +## プライマリ サイトや中央管理サイトのインストール時に求められるライセンス キーはどこから入手できますか？
削除済み

2023-09-01 07:42 UTC, tahakogi commented on articles/mecm/20230818_01.md
> +## Microsoft Intune 製品ファミリの共同管理のライセンスに関する変更点
削除済み

2023-09-01 07:42 UTC, tahakogi commented on articles/mecm/20230818_01.md
> +サイト自体を新規インストールする場合には VLSC から旧環境構築時に利用したプロダクト キーを入手いただいて利用ください。
追記済み

2023-09-01 07:42 UTC, tahakogi commented on articles/mecm/20230818_01.md
> +>以前にSystem Center Configuration Manager に対して持っていたライセンスは、引き続き Microsoft Configuration Managerに適用されます。 新しいサイトをインストールする場合は、既存のプロダクト キーを使用してください。
追加済み

2023-09-01 07:43 UTC, tahakogi commented
修正しましたので再度レビューをお願いします。

2023-09-28 06:24 UTC, tahakogi commented
Pull request が動作しなくなったのでいったん取り下げて出し直しますね

2023-09-28 06:33 UTC, closed without merging