System Center 2012 Configuration Manager における MIF ファイルによるインベントリ拡張について
jpmem/blog pull request #82
Opened 2021-10-06 05:31 UTC by kojiyamada0811

レビューお願いします！

2021-10-06 05:33 UTC, kojiyamada0811 commented
/ok-to-preview sha=1e669a87

2021-10-07 07:59 UTC, yuhonda requested changes
4点修正お願いします。

2021-10-07 07:59 UTC, yuhonda commented on articles/mecm/20211001_01.md
> +title: System Center 2012 Configuration Manager における MIF ファイルによるインベントリ拡張について
タイトル変更してください

2021-10-07 07:59 UTC, yuhonda commented on articles/mecm/20211001_01.md
> +こんにちは。システムセンター サポート担当の本田です。
Configuration Manager サポート担当に変えてください。

2021-10-07 07:59 UTC, yuhonda commented on articles/mecm/20211001_01.md
> +
コード記法でお願いします。

2021-10-07 07:59 UTC, yuhonda commented on articles/mecm/20211001_01.md
> +----- 抜粋ここから -----
抜粋は、> で書きましょう

2021-10-07 08:07 UTC, kojiyamada0811 commented on articles/mecm/20211001_01.md
> +title: System Center 2012 Configuration Manager における MIF ファイルによるインベントリ拡張について
変更しました

2021-10-13 06:11 UTC, kojiyamada0811 commented on articles/mecm/20211001_01.md
> +こんにちは。システムセンター サポート担当の本田です。
修正しました。

2021-10-13 06:11 UTC, kojiyamada0811 commented on articles/mecm/20211001_01.md
> +
修正しました。

2021-10-19 03:36 UTC, merged

2021-10-19 03:36 UTC, yuhonda commented
Approved